[package]
name = "event-listener-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
tokio.workspace = true
futures-util.workspace = true
utils.workspace = true
anyhow.workspace = true
