[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
hex = "0.4.3"
web3 = "0.19.0"
num-bigint = "0.4"
thiserror = "2.0.12"
dotenv = "0.15.0"
